workflows:
  ios-workflow:
    name: iOS PaymentApp Build
    max_build_duration: 30
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build iOS App
        script: |
          xcodebuild archive \
            -project PaymentApp.xcodeproj \
            -scheme PaymentApp \
            -archivePath PaymentApp.xcarchive \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Export IPA
        script: |
          mkdir -p Payload
          cp -r PaymentApp.xcarchive/Products/Applications/PaymentApp.app Payload/
          zip -r PaymentApp.ipa Payload/
    artifacts:
      - PaymentApp.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true